"""Result quality: spam/mirror filtering and domain diversity.

Pure functions over search-result lists (dicts carrying a ``url``), so they are
trivially testable and safe to run under any interpreter. Configuration is
read lazily from env at call time (never at import), and every function takes
explicit ``blocked``/``allowed``/``max_per_domain`` args for tests and for
callers that want deterministic behavior.

Semantics mirrored from the community web-search-plus plugin, simplified to the
parts that matter for a single search source:

- ``filter_spam``  — drop results whose registrable domain is a known content
  mirror / SEO-scraper, or any operator-listed domain. ``allowed`` always wins.
- ``diversify``    — cap results per registrable domain; overflow is moved
  behind the "diverse head", preserving first-occurrence order.

Explicit-intent queries (``site:``, ``include_domains``) bypass both, matching
the upstream convention that a constrained search is already deliberate.
"""
from __future__ import annotations

import os
import re
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlparse

# ---------------------------------------------------------------------------
# Domain utilities (stdlib-only eTLD+1 heuristic, no publicsuffix dependency)
# ---------------------------------------------------------------------------

# Second-level TLD markers before a 2-letter ccTLD that extend the suffix, e.g.
# foo.co.uk, bar.com.au. Combined with a lone ccTLD they make a compound suffix.
_SECOND_LEVEL_TLDS = {
    "co", "com", "org", "net", "gov", "edu", "ac", "mil", "go", "ne",
    "asso", "gen", "ltd", "id", "name", "conf", "gouv", "gob", "pro",
    "info", "biz", "tm", "nic", "priv", "school", "org", "govt", "jobs",
}


def registrable_domain(url: Optional[str]) -> str:
    """Best-effort eTLD+1 of a URL (host only). Handles ``www.`` prefixes and
    compound suffixes (``co.uk``, ``com.au``). Returns ``""`` for any input that
    does not yield a usable host, so callers can skip it."""
    if not url or not isinstance(url, str):
        return ""
    try:
        parsed = urlparse(url if "://" in url else "//" + url)
        host = (parsed.netloc or parsed.path).split(":")[0].strip(".").lower()
    except Exception:
        return ""
    if not host:
        return ""
    parts = [p for p in host.split(".") if p]
    if len(parts) <= 2:
        return host
    # compound suffix: 2-letter ccTLD preceded by a 2LD marker -> drop both
    if len(parts[-1]) == 2 and parts[-2] in _SECOND_LEVEL_TLDS:
        return ".".join(parts[-3:])
    return ".".join(parts[-2:])


# ---------------------------------------------------------------------------
# Default spam / mirror seed list (grow via WEBRESEARCH_BLOCKED_DOMAINS)
# ---------------------------------------------------------------------------

# Recognized content mirrors and autogenerated SEO-scraper farms. This is a
# conservative seed set — extend it for your corpus with the env var below.
DEFAULT_BLOCKED_DOMAINS = {
    "stackprinter.com",  # Stack Overflow mirror
    "stackprinter.org",
    "stackprinter.net",
    "duplicatequestion.com",
    "scraperwiki.com",
}


def _env_list(name: str) -> set:
    return {d.strip().lower() for d in os.getenv(name, "").split(",") if d.strip()}


def load_blocklist() -> set:
    """Default mirror seed + operator extras (WEBRESEARCH_BLOCKED_DOMAINS, csv)."""
    return DEFAULT_BLOCKED_DOMAINS | _env_list("WEBRESEARCH_BLOCKED_DOMAINS")


def load_allowlist() -> set:
    """Operator override list (WEBRESEARCH_ALLOWED_DOMAINS, csv) — always wins."""
    return _env_list("WEBRESEARCH_ALLOWED_DOMAINS")


def _is_explicit_intent(query: str = "", include_domains=None) -> bool:
    if include_domains:
        return True
    return bool(query and re.search(r"\bsite\s*:", query, re.IGNORECASE))


# ---------------------------------------------------------------------------
# Filtering
# ---------------------------------------------------------------------------

def filter_spam(results: List[Dict[str, Any]], *, blocked=None, allowed=None,
                query: str = "", include_domains=None) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """Remove results whose registrable domain is blocked (mirror/scraper or
    operator-listed). ``allowed`` domains are never removed. An explicit
    ``site:`` query or ``include_domains`` bypasses the filter.

    Returns ``(cleaned, meta)`` where ``meta`` reports the removed rows.
    """
    if blocked is None:
        blocked = load_blocklist()
    if allowed is None:
        allowed = load_allowlist()
    if _is_explicit_intent(query, include_domains):
        return list(results), {"spam_filtered": 0, "bypassed": True}

    blocked = {b.lower() for b in blocked if b}
    allowed = {a.lower() for a in allowed if a}
    cleaned: List[Dict[str, Any]] = []
    removed: List[Dict[str, Any]] = []
    for r in results:
        dom = registrable_domain(r.get("url", ""))
        if dom in allowed:
            cleaned.append(r)
            continue
        if dom in blocked:
            removed.append(r)
            continue
        cleaned.append(r)
    return cleaned, {"spam_filtered": len(removed), "removed": removed,
                     "bypassed": False}


def diversify(results: List[Dict[str, Any]], *, max_per_domain: int = 2
              ) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """Cap results per registrable domain to ``max_per_domain`` (0 = unlimited).
    Overflow rows are moved behind the diverse head, preserving first-occurrence
    order within each group. Returns ``(reordered, meta)``.
    """
    if max_per_domain and max_per_domain < 0:
        max_per_domain = 2
    counter: Dict[str, int] = {}
    head: List[Dict[str, Any]] = []
    overflow: List[Dict[str, Any]] = []
    # stable: original first-seen order preserved; per domain the first
    # max_per_domain rows stay in the head, the rest go to overflow.
    for r in results:
        dom = registrable_domain(r.get("url", ""))
        if not max_per_domain:
            head.append(r)
            continue
        c = counter.get(dom, 0)
        if c < max_per_domain:
            head.append(r)
            counter[dom] = c + 1
        else:
            overflow.append(r)
    return head + overflow, {
        "max_per_domain": max_per_domain,
        "overflow": [r.get("url") for r in overflow],
        "overflow_count": len(overflow),
    }
